"""Seed all 214 Kangxi radicals into the database."""
import pyodbc

CONN_STR = 'DRIVER={ODBC Driver 17 for SQL Server};SERVER=localhost;DATABASE=HanziEcosystem;Trusted_Connection=yes;'

# Format: (character, pinyin, meaning, variants, stroke_count, mnemonic_tip)
RADICALS_214 = [
    ("一","yī","Nhất - Một, số một","",1,"Một nét ngang = số 1"),
    ("丨","shù","Cổn - Nét sổ thẳng","",1,"Một nét dọc thẳng đứng"),
    ("丶","diǎn","Chủ - Điểm, dấu chấm","",1,"Một chấm nhỏ"),
    ("丿","piě","Phiệt - Nét sổ xiên","",1,"Nét phẩy xiên trái"),
    ("乙","yǐ","Ất - Thứ hai","乚乛",1,"Can thứ hai trong Thiên Can"),
    ("亅","jué","Quyết - Nét sổ có móc","",1,"Nét sổ có móc câu"),
    ("二","èr","Nhị - Số hai","",2,"Hai nét ngang = số 2"),
    ("亠","tóu","Đầu - Mái che","",2,"Mái che phía trên đầu"),
    ("人","rén","Nhân - Người","亻",2,"Hình người đang đi"),
    ("儿","ér","Nhi - Trẻ con","",2,"Đôi chân trẻ nhỏ"),
    ("入","rù","Nhập - Vào trong","",2,"Mũi tên đi vào"),
    ("八","bā","Bát - Số tám","",2,"Hai nét tách ra = chia đôi"),
    ("冂","jiōng","Quynh - Vùng biên giới","",2,"Khung bao quanh"),
    ("冖","mì","Mịch - Trùm khăn","",2,"Tấm khăn trùm lên"),
    ("冫","bīng","Băng - Nước đá","",2,"Hai giọt nước đông thành đá"),
    ("几","jǐ","Kỷ - Ghế dựa","",2,"Cái bàn nhỏ"),
    ("凵","qiǎn","Khảm - Há miệng","",2,"Hình cái hộp mở"),
    ("刀","dāo","Đao - Con dao","刂",2,"Hình con dao"),
    ("力","lì","Lực - Sức mạnh","",2,"Cánh tay gồng sức"),
    ("勹","bāo","Bao - Bao bọc","",2,"Tay ôm bao bọc"),
    ("匕","bǐ","Chuỷ - Cái thìa","",2,"Cái muỗng/thìa"),
    ("匚","fāng","Phương - Tủ đựng","",2,"Cái hộp vuông mở"),
    ("匸","xì","Hệ - Che phủ","",2,"Mái che một bên"),
    ("十","shí","Thập - Số mười","",2,"Dấu cộng = mười"),
    ("卜","bo","Bốc - Xem bói","",2,"Vết nứt trên mai rùa"),
    ("卩","jié","Tiết - Đốt tre","㔾",2,"Người quỳ gối"),
    ("厂","chǎng","Hán - Sườn núi","",2,"Vách núi dựng đứng"),
    ("厶","sī","Khư - Riêng tư","",2,"Cuộn tròn riêng tư"),
    ("又","yòu","Hựu - Lại nữa","",2,"Bàn tay phải"),
    ("口","kǒu","Khẩu - Miệng","",3,"Hình cái miệng mở"),
    ("囗","wéi","Vi - Vây quanh","",3,"Khung bao kín"),
    ("土","tǔ","Thổ - Đất","",3,"Cây mọc trên mặt đất"),
    ("士","shì","Sĩ - Kẻ sĩ","",3,"Kẻ sĩ đội mũ"),
    ("夂","zhǐ","Tuy - Đi chậm","",3,"Bước chân chậm rãi"),
    ("夊","suī","Truy - Đến sau","",3,"Chân bước theo sau"),
    ("夕","xī","Tịch - Ban đêm","",3,"Mặt trăng lưỡi liềm"),
    ("大","dà","Đại - To lớn","",3,"Người giang tay = to"),
    ("女","nǚ","Nữ - Phụ nữ","",3,"Người phụ nữ quỳ"),
    ("子","zi","Tử - Con cái","",3,"Em bé được bọc tã"),
    ("宀","gài","Miên - Mái nhà","",3,"Mái nhà che chở"),
    ("寸","cùn","Thốn - Tấc","",3,"Bàn tay đo một tấc"),
    ("小","xiǎo","Tiểu - Nhỏ bé","⺌",3,"Ba hạt nhỏ li ti"),
    ("尢","yóu","Uông - Yếu đuối","尣",3,"Người đi khập khiễng"),
    ("尸","shī","Thi - Xác chết","",3,"Thân người nằm"),
    ("屮","chè","Triệt - Mầm non","",3,"Mầm cây vừa nhú"),
    ("山","shān","Sơn - Núi","",3,"Ba đỉnh núi"),
    ("川","chuān","Xuyên - Sông ngòi","巛",3,"Dòng nước chảy"),
    ("工","gōng","Công - Thợ","",3,"Cái thước thợ"),
    ("己","jǐ","Kỷ - Bản thân","",3,"Sợi chỉ cuộn = mình"),
    ("巾","jīn","Cân - Cái khăn","",3,"Tấm khăn treo"),
    ("干","gàn","Can - Thiên can","",3,"Cái chày giã"),
    ("幺","yāo","Yêu - Nhỏ nhắn","",3,"Sợi chỉ mảnh"),
    ("广","guǎng","Nghiễm - Mái nhà rộng","",3,"Ngôi nhà rộng lớn"),
    ("廴","yǐn","Dẫn - Bước dài","",3,"Bước chân kéo dài"),
    ("廾","gǒng","Củng - Chắp tay","",3,"Hai tay chắp lại"),
    ("弋","yì","Dặc - Bắn cung","",3,"Mũi tên đang bay"),
    ("弓","gōng","Cung - Cái cung","",3,"Hình cây cung"),
    ("彐","jì","Kệ - Đầu con nhím","彑",3,"Đầu con nhím"),
    ("彡","shān","Sam - Lông dài","",3,"Ba sợi lông dài"),
    ("彳","chì","Xích - Bước chân trái","",3,"Bước chân trái"),
    ("心","xīn","Tâm - Tim, lòng","忄",4,"Trái tim đang đập"),
    ("戈","gē","Qua - Vũ khí","",4,"Cây kích/giáo"),
    ("戶","hù","Hộ - Cửa","户",4,"Cánh cửa một bên"),
    ("手","shǒu","Thủ - Tay","扌",4,"Bàn tay mở"),
    ("支","zhī","Chi - Cành cây","",4,"Tay cầm cành cây"),
    ("攴","pū","Phác - Đánh nhẹ","攵",4,"Tay cầm roi đánh"),
    ("文","wén","Văn - Văn chương","",4,"Hoa văn trang trí"),
    ("斗","dòu","Đẩu - Đo lường","",4,"Cái gáo múc nước"),
    ("斤","jīn","Cân - Cái rìu","",4,"Lưỡi rìu bổ gỗ"),
    ("方","fāng","Phương - Hướng","",4,"La bàn chỉ hướng"),
    ("无","wú","Vô - Không có","旡",4,"Không có gì cả"),
    ("日","rì","Nhật - Mặt trời","",4,"Mặt trời tròn sáng"),
    ("曰","yuē","Viết - Nói rằng","",4,"Cái miệng đang nói"),
    ("月","yuè","Nguyệt - Mặt trăng","",4,"Trăng lưỡi liềm"),
    ("木","mù","Mộc - Cây gỗ","",4,"Cây có rễ và cành"),
    ("欠","qiàn","Khiếm - Khuyết thiếu","",4,"Người ngáp = thiếu ngủ"),
    ("止","zhǐ","Chỉ - Dừng lại","",4,"Bàn chân dừng bước"),
    ("歹","dǎi","Đãi - Xấu xa","歺",4,"Xương tàn = xấu"),
    ("殳","shū","Thù - Vũ khí dài","",4,"Tay cầm vũ khí"),
    ("毋","wú","Vô - Chớ, đừng","母",4,"Ngăn cấm, đừng làm"),
    ("比","bǐ","Tỷ - So sánh","",4,"Hai người đứng cạnh"),
    ("毛","máo","Mao - Lông","",4,"Sợi lông/tóc"),
    ("氏","shì","Thị - Họ","",4,"Dòng họ gia tộc"),
    ("气","qì","Khí - Không khí","",4,"Hơi nước bốc lên"),
    ("水","shuǐ","Thủy - Nước","氵",4,"Dòng nước chảy"),
    ("火","huǒ","Hỏa - Lửa","灬",4,"Ngọn lửa cháy"),
    ("爪","zhǎo","Trảo - Móng vuốt","爫",4,"Bàn tay có vuốt"),
    ("父","fù","Phụ - Cha","",4,"Người cha cầm gậy"),
    ("爻","yáo","Hào - Hào (Dịch)","",4,"Hai vạch Kinh Dịch"),
    ("爿","qiáng","Tường - Mảnh gỗ","丬",4,"Miếng gỗ xẻ đôi"),
    ("片","piàn","Phiến - Lá, mảnh","",4,"Mảnh gỗ mỏng"),
    ("牙","yá","Nha - Răng","",4,"Chiếc răng nanh"),
    ("牛","niú","Ngưu - Con trâu/bò","牜",4,"Đầu trâu có sừng"),
    ("犬","quǎn","Khuyển - Con chó","犭",4,"Con chó đứng"),
    ("玄","xuán","Huyền - Màu đen","",5,"Sợi tơ đen huyền bí"),
    ("玉","yù","Ngọc - Ngọc bích","王",5,"Ba viên ngọc xâu chuỗi"),
    ("瓜","guā","Qua - Quả dưa","",5,"Quả dưa treo dây"),
    ("瓦","wǎ","Ngõa - Ngói","",5,"Viên ngói trên mái"),
    ("甘","gān","Cam - Ngọt","",5,"Miệng nếm vị ngọt"),
    ("生","shēng","Sinh - Sống, đẻ","",5,"Mầm cây mọc lên = sống"),
    ("用","yòng","Dụng - Sử dụng","",5,"Hàng rào = dùng được"),
    ("田","tián","Điền - Ruộng","",5,"Thửa ruộng chia ô"),
    ("疋","pǐ","Sơ - Chân","",5,"Bàn chân bước đi"),
    ("疒","nè","Nạch - Bệnh tật","",5,"Người nằm trên giường bệnh"),
    ("癶","bō","Bát - Hai chân","",5,"Hai bàn chân đối nhau"),
    ("白","bái","Bạch - Màu trắng","",5,"Tia sáng trắng"),
    ("皮","pí","Bì - Da","",5,"Lớp da bóc ra"),
    ("皿","mǐn","Mãnh - Bát dĩa","",5,"Cái bát trên bàn"),
    ("目","mù","Mục - Mắt","",5,"Con mắt đang nhìn"),
    ("矛","máo","Mâu - Cái mâu","",5,"Cây giáo nhọn"),
    ("矢","shǐ","Thỉ - Mũi tên","",5,"Mũi tên trên cung"),
    ("石","shí","Thạch - Đá","",5,"Hòn đá dưới vách"),
    ("示","shì","Thị - Thần linh","礻",5,"Bàn thờ thần linh"),
    ("禸","róu","Nhựu - Vết chân","",5,"Dấu chân thú"),
    ("禾","hé","Hòa - Lúa","",5,"Bông lúa chín vàng"),
    ("穴","xué","Huyệt - Hang","",5,"Cửa hang động"),
    ("立","lì","Lập - Đứng","",5,"Người đứng trên đất"),
    ("竹","zhú","Trúc - Tre","⺮",6,"Hai nhánh tre"),
    ("米","mǐ","Mễ - Gạo","",6,"Hạt gạo tách vỏ"),
    ("糸","mì","Mịch - Sợi tơ","纟",6,"Cuộn tơ nhỏ"),
    ("缶","fǒu","Phẫu - Cái vò","",6,"Cái bình gốm"),
    ("网","wǎng","Võng - Cái lưới","罒",6,"Tấm lưới bắt cá"),
    ("羊","yáng","Dương - Con dê","⺶",6,"Đầu dê có sừng"),
    ("羽","yǔ","Vũ - Lông vũ","",6,"Đôi cánh chim"),
    ("老","lǎo","Lão - Già","耂",6,"Ông lão chống gậy"),
    ("而","ér","Nhi - Mà, và","",6,"Bộ râu dài"),
    ("耒","lěi","Lỗi - Cái cày","",6,"Cái cày gỗ"),
    ("耳","ěr","Nhĩ - Tai","",6,"Lỗ tai đang nghe"),
    ("聿","yù","Duật - Cây bút","⺺",6,"Tay cầm bút viết"),
    ("肉","ròu","Nhục - Thịt","⺼",6,"Miếng thịt có vân"),
    ("臣","chén","Thần - Bề tôi","",6,"Mắt cúi xuống = phục tùng"),
    ("自","zì","Tự - Mình","",6,"Mũi = chỉ vào mình"),
    ("至","zhì","Chí - Đến","",6,"Mũi tên chạm đích"),
    ("臼","jiù","Cữu - Cái cối","",6,"Cái cối giã gạo"),
    ("舌","shé","Thiệt - Cái lưỡi","",6,"Cái lưỡi thè ra"),
    ("舛","chuǎn","Suyễn - Trái ngược","",6,"Hai chân đi ngược"),
    ("舟","zhōu","Chu - Con thuyền","",6,"Con thuyền nhỏ"),
    ("艮","gèn","Cấn - Dừng lại","",6,"Con mắt nhìn lui"),
    ("色","sè","Sắc - Màu sắc","",6,"Người quỳ = sắc đẹp"),
    ("艸","cǎo","Thảo - Cỏ","艹",6,"Hai ngọn cỏ mọc"),
    ("虍","hū","Hô - Vằn hổ","",6,"Vằn trên lưng hổ"),
    ("虫","chóng","Trùng - Côn trùng","",6,"Con sâu bọ"),
    ("血","xuè","Huyết - Máu","",6,"Bát đựng máu cúng"),
    ("行","xíng","Hành - Đi","",6,"Ngã tư đường"),
    ("衣","yī","Y - Áo quần","衤",6,"Chiếc áo có vạt"),
    ("襾","yà","Á - Che phủ","覀",6,"Tấm vải che"),
    ("見","jiàn","Kiến - Thấy","见",7,"Con mắt trên chân = nhìn"),
    ("角","jiǎo","Giác - Sừng","",7,"Sừng thú nhọn"),
    ("言","yán","Ngôn - Lời nói","讠",7,"Miệng phát ra lời"),
    ("谷","gǔ","Cốc - Thung lũng","",7,"Khe núi sâu"),
    ("豆","dòu","Đậu - Hạt đậu","",7,"Cái bát đựng đậu"),
    ("豕","shǐ","Thỉ - Con heo","",7,"Con heo đang chạy"),
    ("豸","zhì","Trãi - Thú dữ","",7,"Thú có vuốt dài"),
    ("貝","bèi","Bối - Vỏ sò","贝",7,"Vỏ sò = tiền cổ"),
    ("赤","chì","Xích - Màu đỏ","",7,"Lửa + người = đỏ mặt"),
    ("走","zǒu","Tẩu - Chạy","",7,"Người chạy nhanh"),
    ("足","zú","Túc - Chân","⻊",7,"Bàn chân đang bước"),
    ("身","shēn","Thân - Thân thể","",7,"Thân người có bụng"),
    ("車","chē","Xa - Xe cộ","车",7,"Chiếc xe có bánh"),
    ("辛","xīn","Tân - Cay","",7,"Mũi kim = đau, cay"),
    ("辰","chén","Thần - Sáng sớm","",7,"Buổi sáng tinh sương"),
    ("辵","chuò","Sước - Đi","⻌",7,"Bước đi trên đường"),
    ("邑","yì","Ấp - Thành phố","⻏",7,"Người quỳ trong thành"),
    ("酉","yǒu","Dậu - Rượu","",7,"Vò rượu lên men"),
    ("釆","biàn","Biện - Phân biệt","",7,"Dấu chân thú"),
    ("里","lǐ","Lý - Dặm, làng","",7,"Ruộng + đất = làng"),
    ("金","jīn","Kim - Vàng, kim loại","钅",8,"Cục vàng trong đất"),
    ("長","cháng","Trường - Dài","长",8,"Mái tóc dài"),
    ("門","mén","Môn - Cửa","门",8,"Cánh cửa đôi"),
    ("阜","fù","Phụ - Gò đất","⻖",8,"Ngọn đồi nhỏ"),
    ("隶","lì","Đãi - Nô lệ","",8,"Tay bắt người = nô lệ"),
    ("隹","zhuī","Chuy - Chim","",8,"Con chim đuôi ngắn"),
    ("雨","yǔ","Vũ - Mưa","",8,"Giọt mưa rơi từ mây"),
    ("青","qīng","Thanh - Xanh","",8,"Cỏ xanh dưới trăng"),
    ("非","fēi","Phi - Không phải","",8,"Hai cánh trái chiều = sai"),
    ("面","miàn","Diện - Mặt","",9,"Khuôn mặt trong khung"),
    ("革","gé","Cách - Da thuộc","",9,"Tấm da bò thuộc"),
    ("韋","wéi","Vi - Da mềm","韦",9,"Da mềm cuộn tròn"),
    ("韭","jiǔ","Cửu - Hẹ","",9,"Cây hẹ mọc thành hàng"),
    ("音","yīn","Âm - Âm thanh","",9,"Miệng phát ra âm"),
    ("頁","yè","Hiệt - Trang, đầu","页",9,"Đầu người = trang sách"),
    ("風","fēng","Phong - Gió","风",9,"Con trùng bay trong gió"),
    ("飛","fēi","Phi - Bay","飞",9,"Đôi cánh bay lên"),
    ("食","shí","Thực - Ăn","饣",9,"Bát cơm có nắp"),
    ("首","shǒu","Thủ - Đầu","",9,"Cái đầu có tóc"),
    ("香","xiāng","Hương - Thơm","",9,"Lúa chín thơm ngào ngạt"),
    ("馬","mǎ","Mã - Ngựa","马",10,"Con ngựa đang phi"),
    ("骨","gǔ","Cốt - Xương","",10,"Bộ xương trong thịt"),
    ("高","gāo","Cao - Cao","",10,"Tòa nhà cao tầng"),
    ("髟","biāo","Tiêu - Tóc dài","",10,"Mái tóc dài bay"),
    ("鬥","dòu","Đấu - Đánh nhau","",10,"Hai người đánh nhau"),
    ("鬯","chàng","Sưởng - Rượu thơm","",10,"Bình rượu thảo mộc"),
    ("鬲","lì","Cách - Cái vạc","",10,"Nồi nấu ba chân"),
    ("鬼","guǐ","Quỷ - Ma quỷ","",10,"Con quỷ đáng sợ"),
    ("魚","yú","Ngư - Cá","鱼",11,"Con cá bơi dưới nước"),
    ("鳥","niǎo","Điểu - Chim","鸟",11,"Con chim đậu cành"),
    ("鹵","lǔ","Lỗ - Muối","卤",11,"Hạt muối kết tinh"),
    ("鹿","lù","Lộc - Con hươu","",11,"Con hươu có sừng"),
    ("麥","mài","Mạch - Lúa mì","麦",11,"Bông lúa mì vàng"),
    ("麻","má","Ma - Cây gai","",11,"Sợi gai phơi dưới mái"),
    ("黃","huáng","Hoàng - Màu vàng","黄",12,"Ánh sáng vàng rực"),
    ("黍","shǔ","Thử - Kê","",12,"Cây kê chín vàng"),
    ("黑","hēi","Hắc - Màu đen","",12,"Lửa cháy thành muội đen"),
    ("黹","zhǐ","Chỉ - Thêu","",12,"Đường kim mũi chỉ"),
    ("黽","mǐn","Mãnh - Con ếch","黾",13,"Con ếch nhìn từ trên"),
    ("鼎","dǐng","Đỉnh - Cái đỉnh","",13,"Cái vạc đồng ba chân"),
    ("鼓","gǔ","Cổ - Cái trống","",13,"Tay đánh trống rộn ràng"),
    ("鼠","shǔ","Thử - Con chuột","",13,"Con chuột có răng nhọn"),
    ("鼻","bí","Tỵ - Mũi","",14,"Cái mũi = chỉ mình"),
    ("齊","qí","Tề - Đều nhau","齐",14,"Lúa mọc đều hàng"),
    ("齒","chǐ","Xỉ - Răng","齿",15,"Hàm răng trắng"),
    ("龍","lóng","Long - Rồng","龙",16,"Con rồng uốn lượn"),
    ("龜","guī","Quy - Rùa","龟",16,"Con rùa có mai"),
    ("龠","yuè","Dược - Ống sáo","",17,"Ống sáo thổi nhạc"),
]

def seed():
    conn = pyodbc.connect(CONN_STR)
    cursor = conn.cursor()
    
    # Get existing radicals
    cursor.execute("SELECT character FROM Radicals")
    existing = {row.character.strip() for row in cursor.fetchall()}
    
    inserted = 0
    updated = 0
    for char, pinyin, meaning, variants, strokes, tip in RADICALS_214:
        if char in existing:
            cursor.execute(
                "UPDATE Radicals SET pinyin=?, meaning=?, variants=?, stroke_count=?, mnemonic_tip=? WHERE character=?",
                (pinyin, meaning, variants, strokes, tip, char)
            )
            updated += 1
        else:
            cursor.execute(
                "INSERT INTO Radicals (character, pinyin, meaning, variants, stroke_count, mnemonic_tip) VALUES (?,?,?,?,?,?)",
                (char, pinyin, meaning, variants, strokes, tip)
            )
            inserted += 1
    
    conn.commit()
    print(f"Done! Inserted: {inserted}, Updated: {updated}, Total: {inserted + updated}")
    
    cursor.execute("SELECT COUNT(*) FROM Radicals")
    print(f"Total radicals in DB: {cursor.fetchone()[0]}")
    conn.close()

if __name__ == "__main__":
    seed()
